name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          REACT_APP_HELLO: ${{secrets.REACT_APP_HELLO}}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build
